import uuid from 'uuid/v1';
export const EXPERIENCES = [
	{
		id: uuid(),
		company: 'Codepath',
		title: 'Android Teaching Assistant',
		location: 'US Remote',
		date: 'February 2020 - May 2020',
		primaryColor: '#00B27C',
		secondaryColor: '#45D8AA',
		contrastTextColor: '#314850',
		bullets: [
			'Provided fast and effective remote live technical support to over 100 students by helping them with their android projects and assingments throught Slack and Zoom ',
			'Improved and updated android documentation and guides for better student understanding',
			'Guided and taught students tips and tricks on how to effectively use Android Studio for efficient and fast android development ',
			'Helped students to reinforce their understanding of core android concepts, Android Architecture, APIs, Database in Parse and Git & Github by providing 1:1 Zoom sessions',
			'Provided constructive feedback to students and ideas to implement to improve their applications',
			'Achieved a record NPS score of 79 for the android program',
		],
	},
	{
		id: uuid(),
		company: 'Codecademy',
		title: 'SWE Intern',
		location: 'New York, NY',
		date: 'June 2019 - August 2019',
		primaryColor: '#204055',
		secondaryColor: '#325f7d',
		contrastTextColor: '#5FE6CA',
		bullets: [
			'Co-engineered the new Code Challenges feature, an assessment type that allows learners to type and execute code to reinforce their knowledge',
			'Demoed the Code Challenges MVP to the company stakeholders in the monthly all-hands meeting',
			'Took initiative and stepped forward to contribute to the migration of React components and Javascript files to Typescript',
			'Collaborated with designers and engineers to launch a new interactive 404 page that renders a custom endless runner game built with PhaserJS',
			'Worked on frontend improvements including redesigning the footer and catalog, converting legacy .erb pages to react and fixing accessibility bugs',
			'Reviewed and tested production-ready code. Utilized Jest and Enzyme for unit and component testing, TestCafe for E2E testing and RSpec for rails',
		],
	},
	{
		id: uuid(),
		company: 'Coding Hub',
		title: 'President and Cofounder',
		location: 'Plattsburgh, NY',
		date: 'September 2018 - Present',
		primaryColor: '#E66363',
		secondaryColor: '#F8959D',
		contrastTextColor: '#E6DC63',
		bullets: [
			'Spearhead an agile team of 20 members to plan, build, test and deploy 4 software apps to assist students and organizations on campus',
			'Establish coding standards and write detailed documentation to make applications maintainable and allow new members to quickly understand and collaborate on the projects',
			'Successfully explain highly-technical concepts to university staff to gain approval and receive support to deploy our applications',
			'Conduct bi-weekly stand-up meetings and encourage team collaboration through code reviews, pair programming, and weekly lightning talks',
			'Introduce and set up CI/CD pipeline with CircleCI in our workflow to improve development speed and ensure code quality',
			'Introduce and use Slack and Asana for team and project management',
		],
	},
	{
		id: uuid(),
		company: 'Interbank',
		title: 'Data Analyst Intern',
		location: 'Lima, PE',
		date: 'June 2018 - August 2018',
		primaryColor: '#09A24F',
		secondaryColor: '#00C55B',
		contrastTextColor: '#0339A6',
		bullets: [
			'Developed a supervised ML text classifier with python to process customer reviews with an accuracy of 92% as measured by a confusion matrix',
			'Built over 15 fully responsive in-apps and pop-ups for the bank app and website using HTML5, CSS3 and vanilla JS for A/B testing and experiments',
			'Proactively participated in committee meetings to show and analyze weekly results as well as propose and discuss new experiments',
		],
	},
	{
		id: uuid(),
		company: 'Computer Science Departent',
		title: 'Teaching Assisstant',
		location: 'Plattsburgh, NY',
		date: 'January 2019 - December 2020',
		primaryColor: '#EBB523',
		secondaryColor: '#EBC14D',
		contrastTextColor: '#25917D',
		bullets: [
			'Aided 50+ students in their understanding of core programming concepts and projects using Python and C',
			'Held office hours twice a week and provide one-on-one support to computer science students for CSC221 (Intro to programming) and CSC309 (C language)',
			'Collaborated with the professor to review syllabus and class understunding',
			'Provided extra resources and excercises to student to improve and review class material',
		],
	},
];
